name: Mind Your Stonks

on:
  push:
    branches: 
      - test

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        echo $PWD
        openssl enc aes-256-cbc -d -pass pass:${{ secrets.sheet_password }} -in client_secret.enc -out client_secret.json
        pip install selenium
        wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
        mkdir geckodriver
        tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
        ls geckodriver
        chmod +x geckodriver/geckodriver
        sudo cp geckodriver/geckodriver /usr/local/bin
        which geckodriver
        echo $PATH
        geckodriver --version || exit 1
        pip install gspread
        pip install --upgrade oauth2client
        pip install aenum
        pip install loguru
        pip install psutil
    - name: Install repo
      run: |
        pip install .
    - name: Read balance
      run: |
        query_balance.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }}
    # if: github.ref != 'refs/heads/master'
    - name: Publish sheets
      run: |
        query_balance.py ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }} --update-spreadsheet ./client_secret.json
    #  if: github.ref == 'refs/heads/master'
